### ISSUE TITLE
CSS基础盒模型 CSS basic box model

### ISSUE THREAD

**Issue by cemcoe** [cemcoe/cemcoe.github.io#31]
首先需要明确的是CSS盒模型分为两种，由box-sizing的属性值控制。
content-box  是默认值。在添加border或者padding时，如果计算失误，会出现盒子被撑开或者被挤到下一行的现象。
border-box border和padding的值是包含在width内的。在视觉上盒子的宽度就是width的值。但是当border或者padding的值大于width时，盒子的视觉宽度将不再由width控制
现有一盒子模型如下：
```css
.box {
        width: 50px;
        height: 50px;
        background-color: rgb(0, 0, 0);
        padding-top: 20px;
        margin: 20px;
        border: 10px solid rgb(0, 0, 0);
    }
```
content-box
![Snipaste_2019-06-07_16-12-10](https://user-images.githubusercontent.com/29108504/59090364-2d738080-893f-11e9-94c9-e2fa93271dc1.png)

border-box
![Snipaste_2019-06-07_16-11-37](https://user-images.githubusercontent.com/29108504/59090394-4714c800-893f-11e9-8403-1f99815f2a5b.png)

border值过大而失控的border-box
```css
.box {
        width: 50px;
        height: 50px;
        background-color: rgb(0, 0, 0);
        padding-top: 20px;
        margin: 20px;
        border: 40px solid rgb(0, 0, 0);
        box-sizing: border-box;
    }
```
![Snipaste_2019-06-07_16-26-27](https://user-images.githubusercontent.com/29108504/59091045-074ee000-8941-11e9-8619-09b5ae3abebe.png)

## 关于padding
在使用百分比时相对的是宽度计算
实现2:1的矩形块
```css
.box {
        padding: 25% 50%;
        background-color: rgb(0, 0, 0);
        
    }
```
