### ISSUE TITLE
三列布局，两端固定，中间自适应

### ISSUE THREAD

**Issue by cemcoe** [cemcoe/cemcoe.github.io#33]
# 两端固定，中间自适应
盒子relative，两端盒子absolute，并设定固定宽度，中间盒子宽度auto，左右的margin只分别设为左右盒子的固定宽度值

html结构
```
<div class="container">
   <div class="left">this is left</div>
   <div class="center">this is center</div>
   <div class="right">this is right</div>
</div>
```

然后是css

```css
.container {
  width: 100%;
  height: 60px;
  border-bottom: 1px solid #000;
  position: relative;
}
.left {
  position: absolute;
  left: 0;
  top: 0;
  width: 60px;
  height: 60px;
  background-color: #000;
}

.center {
  width: auto;
  margin: 0 60px;
  height 60px
  background-color: blue;
}

.right {
  position: absolute;
  top: 0;
  right: 0;
  width: 60px;
  height: 60px;
  background-color: #f40;
}

```
